'use client';
import React, { useEffect, useState } from 'react';
import { Users, Clock, TableProperties } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';

export default function OperationsDashboard() {
  const [data, setData] = useState<any>(null);
  const [query, setQuery] = useState('');
  const load = React.useEffectEvent(async () => { const response = await fetch('/api/admin/operations'); if (response.ok) setData(await response.json()); });
  useEffect(() => { const timeout = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timeout); }, []);
  useEffect(() => { const supabase = createClient(); const channel = supabase.channel('daily-operations').on('postgres_changes', { event: '*', schema: 'public', table: 'reservations' }, () => void load()).on('postgres_changes', { event: '*', schema: 'public', table: 'reservation_table_assignments' }, () => void load()).on('postgres_changes', { event: '*', schema: 'public', table: 'waitlist_entries' }, () => void load()).subscribe(); return () => { void supabase.removeChannel(channel); }; }, []);
  if (!data) return <p className="p-8 text-sm">Carregando operação...</p>;
  const reservations = data.reservations || [];
  const count = (status: string) => reservations.filter((item: any) => item.status === status).length;
  const people = reservations.filter((item: any) => !['cancelled','no_show'].includes(item.status)).reduce((sum: number, item: any) => sum + item.num_guests, 0);
  const action = async (id:string, action:string) => { await fetch(`/api/reservations/${id}`, { method:'PATCH', headers:{'Content-Type':'application/json'}, body:JSON.stringify({action}) }); await load(); };
  const visible = reservations.filter((item:any) => `${item.name} ${item.whatsapp} ${item.reservation_time}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="space-y-6"><div className="rounded-3xl bg-white p-6 border border-[#D9CFC1]"><h2 className="text-xl font-bold">Operação de hoje</h2><p className="text-sm text-[#4A3728]/60">Recepção, mesas e próximos atendimentos.</p><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar nome, telefone ou horário" className="mt-4 w-full rounded-xl bg-[#F5F2ED] px-4 py-3 text-sm"/></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label="Reservas" value={reservations.length}/><Metric label="Pessoas" value={people}/><Metric label="Chegaram" value={reservations.filter((item:any)=>item.arrived_at).length}/><Metric label="Sentadas" value={count('seated')}/><Metric label="Concluídas" value={count('completed')}/><Metric label="No-show" value={count('no_show')}/><Metric label="Canceladas" value={count('cancelled')}/><Metric label="Fila" value={(data.waitlist||[]).length}/></div><section className="rounded-3xl border border-[#D9CFC1] bg-white"><header className="border-b border-[#D9CFC1] p-5 font-bold"><Clock className="mr-2 inline" size={17}/>Timeline</header>{visible.map((item:any)=><div key={item.id} className="border-b border-[#D9CFC1]/50 p-4 text-sm"><div className="flex items-center justify-between"><span className="font-bold">{item.reservation_time.slice(0,5)} · {item.name}</span><span>{item.num_guests} pessoas · {item.status}</span></div><div className="mt-2 flex flex-wrap gap-2">{item.status==='pending'&&<button onClick={()=>void action(item.id,'confirm')}>Confirmar</button>}{!item.arrived_at&&['pending','confirmed'].includes(item.status)&&<button onClick={()=>void action(item.id,'arrive')}>Chegou</button>}{item.status==='confirmed'&&<button onClick={()=>void action(item.id,'seat')}>Sentar</button>}{item.status==='seated'&&<button onClick={()=>void action(item.id,'complete')}>Finalizar</button>}{item.status==='confirmed'&&<button onClick={()=>void action(item.id,'no_show')}>No-show</button>}</div></div>)}</section><section className="rounded-3xl border border-[#D9CFC1] bg-white"><header className="border-b border-[#D9CFC1] p-5 font-bold"><TableProperties className="mr-2 inline" size={17}/>Mesas</header>{(data.tables||[]).map((table:any)=><div key={table.id} className="flex justify-between border-b border-[#D9CFC1]/50 p-4 text-sm"><span>{table.restaurant_areas?.name} · {table.code}</span><span>{table.max_capacity} lugares</span></div>)}</section></div>;
}
function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-2xl border border-[#D9CFC1] bg-white p-4"><p className="text-[10px] font-bold uppercase text-[#4A3728]/50">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></div>; }
